### ISSUE TITLE
imresize has been removed from scipy

### ISSUE THREAD

**Issue by atitus** [tboudreaux/mpl_animate#2]
Importing mplEasyAnimate  like this:

```
from mplEasyAnimate import animation
from tqdm import tqdm
```
gives this error:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-9a4060da22c6> in <module>
----> 1 from mplEasyAnimate import animation
      2 from tqdm import tqdm

/anaconda3/envs/mathmodel/lib/python3.7/site-packages/mplEasyAnimate/__init__.py in <module>
      2 mplEasyAnimate
      3 """
----> 4 from .animate import animation, autoAnimation
      5 

/anaconda3/envs/mathmodel/lib/python3.7/site-packages/mplEasyAnimate/animate.py in <module>
      2 import numpy as np
      3 import imageio
----> 4 from scipy.misc import imresize
      5 from tqdm import tqdm
      6 import matplotlib

ImportError: cannot import name 'imresize' from 'scipy.misc' (/anaconda3/envs/mathmodel/lib/python3.7/site-packages/scipy/misc/__init__.py)
```

According to [this issue](https://github.com/scipy/scipy/issues/6212), `resize` has been removed.

I'm going to install an older version of scipy for now. But I wonder if it's possible to update mplEasyAnimate to work with the newer version of scipy.

Thanks for making mplEasyAnimate. It's a great package.

**Comment by tboudreaux** [comment]
Thank you,

scipy.misc.imresize has been replaced with skimage.transform.resize in animate.py. Due to this there has also been additional data type checks have been put in place to make sure that images stay with pixel values in the range between 0 and 255 internally.

Best
